version: "3.8"

services:
  client:
    build:
      context: ./client/reactclient
      args:
        - VITE_ENV=docker
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
